### ISSUE TITLE
Unable to show the results with custom soulmate instance

### ISSUE THREAD

**Issue by aroop** [mcrowe/soulmate.js#1]
Hi,

I have been trying to get solumate.js working in my application and in the demo page. I am using solumate as a rack mount in a rails application. Solumate seems to be sending the json right but solumate.js is not able to show the results. 

The results from the server is available [here](https://skitch.com/aroop/gun5s/localhost-3001-sm-search-callback-jquery16408981715778354555-1324454856478andterm-tesandtypes-5b-5d-movieandlimit-5). And headers from the server is available [here](https://skitch.com/aroop/gun7b/developer-tools-file-localhost-users-ajay-development-os-soulmate.js-demo-index.html)

I tried in both the the demo page by changing the url and in my application and the result seems to be consistent. 

I don't see any error in the browser console before sending a request or after the server responds. I have tested in firefox, chrome and safari.

Any help would be appreciated.

Thanks,
Ajay Kumar

**Comment by mcrowe** [comment]
Hi Ajay,

Thanks for being the first other than me to try this plugin out! I'll try to check this issue out today.

Cheers,
Mitch

**Comment by mcrowe** [comment]
In the meantime, could you let me know if the specs pass for you by opening spec/spec_runner.html in your browser?

**Comment by aroop** [comment]
Looks like no issues with the specs. I see 76 specs, 0 failures in 0.086sFinished at Wed Dec 21 2011 09:33:08 GMT-0800 (PST)

Let me know if you want me to tunnel my localhost to a public url so that you can see it in browser.

**Comment by mcrowe** [comment]
Strange. The response and headers look about how I would expect them to, and simulating that response on my end, I wasn't able to re-create the problem unfortunately. 

Definitely, if I could access your soulmate through a public url that would be a huge help. Feel free to shoot a url to my email at crowe.mitch@gmail.com , and I'll be able to look into it further.

Which version of soulmate are you using?

Does the demo work for you with other soulmate backends? I'm sure the seatgeek guys wouldn't mind if you fire a couple test requests to their autocomplete system, using url => 'http://seatgeek.com/autocomplete', types => ['event'] . Let me know if that works.

In case you want to get your hands a little dirty you could likely narrow the issue down by throwing a few log statements to see that requests are being made, and that the success callback is being called. Try adding a console.log line above lines 267 and 277 in jquery.soulmate.js and see what you find.

**Comment by aroop** [comment]
After doing some styling to the suggestbox I could see the results and everything works as expected.

Sorry for wasting your time.

**Comment by mcrowe** [comment]
Hey no worries at all Ajay! I'm glad you're trying it out.
