### ISSUE TITLE
data url 

### ISSUE THREAD

**Issue by wpram** [mcrowe/soulmate.js#11]
Hi,

I need help with adding data url into the redis database in soulmate. Does soulmate.js link to the url? Cause when I see your demo, it doesn't link to the seatgeek search result.

Thanks

**Comment by mcrowe** [comment]
Hi @wpram . Sorry, I honestly never saw this issue until now. My notifications somehow missed it!

soulmate.js does not connect directly to redis. It uses the http API provided by the soulmate gem. Hooking up soulmate to a redis database is explained in the `soulmate` project repo.
